apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-svc
  labels:
    app: postgres
    {{- if .Values.labels.environment }}
    environment: {{ .Values.labels.environment }}
    {{- end }}
spec:
  selector:
    app: postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  type: ClusterIP
