apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Values.labels.app }}
    {{- if .Values.labels.environment }}
    environment: {{ .Values.labels.environment }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
