apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web-deployment
  labels:
    app: flask-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-web
  template:
    metadata:
      labels:
        app: flask-web
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres-svc -p 5432 -U postgres; do
                echo "Waiting for PostgreSQL to be ready..."
                sleep 2
              done
              echo "PostgreSQL is ready!"
      containers:
        - name: flask-web-container
          image: haimgoldman/flask-web:v3.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: flask-web-port
              containerPort: 8000
          env:
            - name: DB_HOST
              value: postgres-svc
            - name: DB_NAME
              value: visitsdb
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: password
            - name: DB_PORT
              value: "5432"