replicaCount: 1

image:
  repository: haimgoldman/flask-web
  tag: v2.0
  pullPolicy: IfNotPresent

container:
  name: flask-web-container
  port: 8000

service:
  type: ClusterIP
  port: 80
  annotations: {}

ingress:
  className: nginx
  host: flask-dev.local
  path: /
  pathType: Prefix
  annotations: {}
  tls: []

deployment:
  annotations: {}

labels:
  app: flask-web
  environment: dev
