replicaCount: 3

image:
  repository: haimgoldman/flask-web
  tag: v3.0
  pullPolicy: IfNotPresent

container:
  name: flask-web-container
  port: 8000

service:
  type: ClusterIP
  port: 80
  annotations: {}

ingress:
  className: nginx
  host: flask.local
  path: /
  pathType: Prefix
  annotations: {}
  tls: []

deployment:
  annotations: {}

postgres:
  image: postgres
  tag: "15"
  database: visitsdb
  user: postgres
  password: password
  storage: 1Gi
  usePersistentVolume: true  # Set to false for EKS without EBS CSI driver

labels:
  app: flask-web
  environment: ""
